### ISSUE TITLE
Criar página ajuda

### ISSUE THREAD

**Issue by 5nebur** [zyoncore/Testes#5]
Criar uma página de ajuda. pois estou tendo muita dificuldade.

**Comment by zyoncore** [comment]
A pagina está em crustução

**Comment by 5nebur** [comment]
Obrigado, estou aguardando
________________________________
De: Rubens Cordeiro ***@***.***>
Enviado: domingo, 27 de junho de 2021 15:26
Para: zyoncore/Testes ***@***.***>
Cc: 5nebur ***@***.***>; Author ***@***.***>
Assunto: Re: [zyoncore/Testes] Criar página ajuda (#5)


A pagina está em crustução

**Comment by 5nebur** [comment]
Estou aguardando @zyoncore

**Comment by zyoncore** [comment]
ok

**Comment by 5nebur** [comment]
obrigado
________________________________
De: Rubens Cordeiro ***@***.***>
Enviado: domingo, 27 de junho de 2021 23:20
Para: zyoncore/Testes ***@***.***>
Cc: 5nebur ***@***.***>; Assign ***@***.***>
Assunto: Re: [zyoncore/Testes] Criar página ajuda (#5)


ok
